controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
# profile:
#     path: /profile/{path}
#     controller: App\Controller\ProfileController::index

